"""E.3 architectural-integrity report builder.

Reads the JSON output of `run_bench.py --json`, produces:

  bench/architectural/REPORT.md   — human-readable, suitable for arxiv
  bench/architectural/report.json — machine-readable artifact

Headline numbers reported:
  - Aether catch rate           = naive-Aether rejections / total
  - Python silent-failure rate  = naive-Python silent-runs / total
  - Aether viability rate       = correct-Aether passes / total
  - Per-axis breakdown          = grouped by B.1 / B.2 / B.3 / B.4 / composition

The report explicitly frames this as a **static baseline** against
the hand-curated "naive agent" candidate corpus, NOT a closed
empirical study against live frontier models. The live-model study
is Phase E.live and scheduled for the close-out path described in
yc/application_v5.md.
"""
from __future__ import annotations
import collections
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
PY = sys.executable


def _run_bench_json():
    r = subprocess.run(
        [PY, "-B", os.path.join(HERE, "run_bench.py"), "--json"],
        cwd=ROOT, capture_output=True, text=True,
    )
    return json.loads(r.stdout), r.returncode


def _per_axis(tasks):
    """Return dict axis -> {n, n_pass}."""
    out = collections.defaultdict(lambda: {"n": 0, "n_pass": 0,
                                           "aether_caught": 0, "python_silent": 0})
    for t in tasks:
        axis = t["axis"]
        out[axis]["n"] += 1
        if t["passed"]:
            out[axis]["n_pass"] += 1
        for v in t["variants"]:
            if v["variant"] == "naive_aether" and v["passed"]:
                out[axis]["aether_caught"] += 1
            if v["variant"] == "naive_python" and v["passed"]:
                out[axis]["python_silent"] += 1
    return dict(out)


def build_report():
    data, rc = _run_bench_json()
    summary = data["summary"]
    tasks = data["tasks"]
    by_axis = _per_axis(tasks)

    md = []
    md.append("# Architectural-Integrity Benchmark — v0.3 baseline report")
    md.append("")
    md.append("**Generated by:** `bench/architectural/build_report.py`")
    md.append("")
    md.append("**Scope.** This is the *static baseline* of the Phase E "
              "benchmark: every task ships with a hand-curated \"naive agent\" "
              "candidate solution that models the typical first-attempt "
              "failure mode an LLM produces. The harness drives the candidate "
              "through both the Aether toolchain and a Python interpreter and "
              "classifies the outcome.")
    md.append("")
    md.append("**Not in scope of this report:** running the same task corpus "
              "against live frontier models. That's Phase E.live, scheduled "
              "alongside the YC application v5 timeline.")
    md.append("")
    md.append("## Headline numbers")
    md.append("")
    md.append(f"- **Aether catch rate:** {summary['aether_catch_rate']} — "
              f"every naive-agent candidate that violates an architectural "
              f"promise is rejected at compile or runtime boundary with a "
              f"structured diagnostic.")
    md.append(f"- **Python silent-failure rate:** "
              f"{summary['python_silent_failure_rate']} — every naive-agent "
              f"candidate runs to exit 0 with the wrong output (no exception, "
              f"no warning).")
    md.append(f"- **Aether viability rate (correct refs):** "
              f"{summary['aether_correct_passes']} — the architecturally-"
              f"correct reference runs cleanly under all default-on passes.")
    md.append(f"- **Python control rate (correct refs):** "
              f"{summary['python_correct_passes']} — sanity check that the "
              f"Python equivalent also runs cleanly.")
    md.append("")
    md.append("## Per-axis breakdown")
    md.append("")
    md.append("| Axis | Tasks | Aether caught | Python silent |")
    md.append("|------|-------|---------------|----------------|")
    for axis in sorted(by_axis):
        a = by_axis[axis]
        md.append(f"| {axis} | {a['n']} | {a['aether_caught']}/{a['n']} "
                  f"| {a['python_silent']}/{a['n']} |")
    md.append("")
    md.append("## Per-task results")
    md.append("")
    md.append("| ID | Axis | Naive Aether | Naive Python | Correct Aether | Correct Python |")
    md.append("|----|------|---------------|---------------|-----------------|-----------------|")
    for t in tasks:
        cells = {v["variant"]: ("ok" if v["passed"] else "FAIL")
                 for v in t["variants"]}
        md.append(f"| {t['id']} | {t['axis']} | "
                  f"{cells.get('naive_aether', '-')} | "
                  f"{cells.get('naive_python', '-')} | "
                  f"{cells.get('correct_aether', '-')} | "
                  f"{cells.get('correct_python', '-')} |")
    md.append("")
    md.append("## Honesty notes")
    md.append("")
    md.append("- The \"naive agent\" candidates are hand-curated by the "
              "Aether team based on the most-common failure shapes seen in "
              "AI-generated code. They are not random samples from an LLM "
              "run. A live-model replication study against this corpus is "
              "Phase E.live work.")
    md.append("- Every Aether rejection corresponds to one of the documented "
              "diagnostic codes (see `grammar/diagnostics.md`); every Python "
              "silent failure produces a stdout that demonstrably violates "
              "the architectural promise stated in the task's README.")
    md.append("- The harness is wired into `scripts/run_all.py`; the headline "
              "numbers above are reproducible from a fresh clone by running "
              "`python3 -B scripts/run_all.py`.")
    md.append("")

    report_path = os.path.join(HERE, "REPORT.md")
    json_path = os.path.join(HERE, "report.json")
    with open(report_path, "w") as f:
        f.write("\n".join(md))
    with open(json_path, "w") as f:
        json.dump({"summary": summary, "by_axis": by_axis,
                   "tasks": [{"id": t["id"], "axis": t["axis"],
                              "passed": t["passed"]} for t in tasks]},
                  f, indent=2)
    print(f"wrote {report_path}")
    print(f"wrote {json_path}")
    return 0 if rc == 0 else 1


if __name__ == "__main__":
    raise SystemExit(build_report())
