"""Aether to Python emitter. Walks the AST and produces runnable Python.

The emitter NEVER emits `import aether.runtime` itself; runnability is
provided by `cli.cmd_run` which exec's the emitted code with the runtime
namespace pre-populated. For standalone use, see `aether emit` plus the
helper in `scripts/run_emitted.py`.
"""

from __future__ import annotations
from typing import Any, Dict, List, Optional, Set, Tuple

from .runtime import mangle


# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------

class EmitContext:
    def __init__(self):
        self.indent_level = 0
        self.lines: List[str] = []
        self.union_cases: Dict[str, str] = {}
        self.record_kinds: Set[str] = set()
        self.fn_name_stack: List[str] = []
        self.tmp_counter = 0
        self.old_exprs_stack: List[List[Tuple[str, str]]] = []
        # Stack of (clause_ast, pretty_text) for the active function so each
        # `return` site can emit the ensures-postcondition asserts.
        self.ensures_stack: List[List[Dict[str, Any]]] = []
        self._pending_helpers: List[str] = []
        # Map of refinement-type-name -> predicate AST. Populated at the
        # start of emit() by walking TypeDecls. Used to insert
        # _ae_check_refinement calls at function entry for parameters whose
        # declared type matches.
        self.refinements: Dict[str, Dict[str, Any]] = {}

    def emit(self, s: str = ""):
        if s:
            self.lines.append("    " * self.indent_level + s)
        else:
            self.lines.append("")

    def block(self):
        ctx = self
        class _B:
            def __enter__(s):
                ctx.indent_level += 1
            def __exit__(s, *a):
                ctx.indent_level -= 1
        return _B()

    def fresh(self, prefix: str = "tmp") -> str:
        self.tmp_counter += 1
        return f"_ae_{prefix}{self.tmp_counter}"


# ----------------------------------------------------------------------
# Public entry point
# ----------------------------------------------------------------------

def emit(ast: Dict[str, Any]) -> str:
    ctx = EmitContext()
    ctx.emit("# Auto-generated by aether emitter v0.1. Do not edit by hand.")
    ctx.emit("# Run via: aether run <file>   (the runtime is injected into globals)")
    ctx.emit()

    # First pass: collect union cases, records, and refinement types.
    for d in ast["decls"]:
        if d["kind"] == "UnionDecl":
            for c in d["cases"]:
                ctx.union_cases[c["name"]] = d["name"]
        elif d["kind"] == "RecordDecl":
            ctx.record_kinds.add(d["name"])
        elif d["kind"] == "TypeDecl" and d.get("refinement") is not None:
            base = d.get("base") or {}
            ctx.refinements[d["name"]] = {
                "predicate": d["refinement"],
                "base_kind": base.get("kind"),
                "base_name": base.get("name"),
            }
    ctx.union_cases.setdefault("Some", "Option")
    ctx.union_cases.setdefault("None", "Option")
    ctx.union_cases.setdefault("Ok", "Result")
    ctx.union_cases.setdefault("Err", "Result")

    # B.4 polish: emit one module-level predicate-helper per refinement type
    # before the user's declarations, so per-call boundary checks can reuse
    # the same callable instead of allocating a fresh lambda per invocation.
    # The helper name is `_ae_refn_<TypeName>`. It's pure and takes _ae_self.
    if ctx.refinements:
        ctx.emit()
        ctx.emit("# refinement predicates (B.4: hoisted helpers)")
        for refn_name, refn_data in ctx.refinements.items():
            pred_src = emit_expr(ctx, refn_data["predicate"])
            ctx.emit(f"def _ae_refn_{refn_name}(_ae_self):")
            with ctx.block():
                ctx.emit(f"return bool({pred_src})")

    # Emit each top-level declaration. After each, flush any helper functions.
    for d in ast["decls"]:
        emit_top_decl(ctx, d)
        if ctx._pending_helpers:
            ctx.lines.extend(ctx._pending_helpers)
            ctx._pending_helpers = []

    # Auto-driver: if a function called 'main' was defined, call it.
    main_present = any(
        d["kind"] == "FunctionDecl" and d["name"] == "main" and not d["params"]
        for d in ast["decls"]
    )
    if main_present:
        ctx.emit()
        ctx.emit('if __name__ == "__main__":')
        with ctx.block():
            ctx.emit(f'{mangle("main")}()')

    return "\n".join(ctx.lines) + "\n"


# ----------------------------------------------------------------------
# Top-level declarations
# ----------------------------------------------------------------------

def emit_top_decl(ctx: EmitContext, d: Dict[str, Any]):
    k = d["kind"]
    if k == "FunctionDecl":
        emit_function(ctx, d)
    elif k == "TypeDecl":
        ctx.emit(f"# type {d['name']} = ... (refinement checked at boundary)")
    elif k == "RecordDecl":
        emit_record_constructor(ctx, d)
    elif k == "UnionDecl":
        emit_union_constructors(ctx, d)
    elif k == "ConstDecl":
        ctx.emit(f"{mangle(d['name'])} = {emit_expr(ctx, d['value'])}")
    elif k == "ModuleDecl":
        ctx.emit(f"# module {d['name']} requires capabilities: {d['capabilities']}")
        ctx.emit(f"# exports: {d['exports']}")
    elif k == "ImportDecl":
        ctx.emit(f"# import {'.'.join(d['path'])}")
    else:
        raise NotImplementedError(f"top-level decl kind: {k}")


def emit_record_constructor(ctx: EmitContext, d: Dict[str, Any]):
    fields = [f["name"] for f in d["fields"]]
    args = ", ".join(fields) if fields else ""
    ctx.emit()
    ctx.emit(f"def {mangle(d['name'])}({args}):")
    with ctx.block():
        kind_lit = repr(d["name"])
        items = ", ".join(f"{f!r}: {f}" for f in fields)
        if items:
            ctx.emit(f'return {{"_kind": {kind_lit}, {items}}}')
        else:
            ctx.emit(f'return {{"_kind": {kind_lit}}}')


def emit_union_constructors(ctx: EmitContext, d: Dict[str, Any]):
    union_name = d["name"]
    ctx.emit()
    ctx.emit(f"# union {union_name}")
    for c in d["cases"]:
        cname = c["name"]
        params = c["params"]
        arg_names = [p["name"] for p in params]
        arg_list = ", ".join(arg_names) if arg_names else ""
        body_args = ", ".join(arg_names)
        ctx.emit(f"def {mangle(cname)}({arg_list}):")
        with ctx.block():
            if body_args:
                ctx.emit(f"return ({cname!r}, {body_args})")
            else:
                ctx.emit(f"return ({cname!r},)")


# ----------------------------------------------------------------------
# Functions
# ----------------------------------------------------------------------

def emit_function(ctx: EmitContext, d: Dict[str, Any]):
    name = d["name"]
    params = [mangle(p["name"]) for p in d["params"]]
    ctx.fn_name_stack.append(name)
    ctx.old_exprs_stack.append([])
    ctx.ensures_stack.append(d["ensures"])
    ctx.emit()
    ctx.emit(f"def {mangle(name)}({', '.join(params)}):")
    with ctx.block():
        eff_lits = []
        for e in d["effects"]:
            eff_lits.append("(" + ", ".join(repr(p) for p in e["path"]) + ",)")
        ctx.emit(f"push_effect_frame([{', '.join(eff_lits)}])")
        old_marker_idx = len(ctx.lines)
        # B.4 polish: refinement boundary checks reference the hoisted
        # `_ae_refn_<TypeName>` helper instead of allocating a lambda per
        # call. The predicate's source text is also passed so the runtime
        # diagnostic can include it: "value 0 fails refinement PositiveInt
        # where self > 0" reads better than "value 0 fails refinement
        # PositiveInt".
        for p in d["params"]:
            ty = p.get("type") or {}
            if ty.get("kind") == "TypeName" and ty.get("name") in ctx.refinements:
                refn_name = ty["name"]
                pname_m = mangle(p["name"])
                pred_ast = ctx.refinements[refn_name]["predicate"]
                pred_text = _pretty(pred_ast)
                ctx.emit(
                    f"_ae_check_refinement({pname_m}, "
                    f"_ae_refn_{refn_name}, "
                    f"{refn_name!r}, {p['name']!r}, {pred_text!r})"
                )
        for clause in d["requires"]:
            cond_src = emit_expr(ctx, clause)
            ctx.emit(f"_ae_assert_contract(bool({cond_src}), 'requires', "
                     f"{repr(_pretty(clause))}, {name!r})")
        ctx.emit("try:")
        with ctx.block():
            if not d["body"]:
                ctx.emit("_ae_result = None")
                emit_ensures_checks(ctx)
                ctx.emit("return _ae_result")
            else:
                emit_block(ctx, d["body"])
                # Implicit fall-through: only emit if the body could fall through.
                # If the last statement is unconditionally a `return`, the
                # fall-through path is dead and emitting it duplicates the
                # ensures check (also creating a redundant old() snapshot).
                if not _body_terminates(d["body"]):
                    ctx.emit("_ae_result = None")
                    emit_ensures_checks(ctx)
                    ctx.emit("return _ae_result")
        ctx.emit("finally:")
        with ctx.block():
            ctx.emit("pop_effect_frame()")

        old_pairs = ctx.old_exprs_stack[-1]
        if old_pairs:
            # old() snapshots are inserted at the function's body level
            # (same indent as `push_effect_frame`), which is the current
            # `ctx.indent_level` while we're still inside the
            # `with ctx.block()` for the function body.
            old_lines = []
            for old_var, old_src in old_pairs:
                old_lines.append("    " * ctx.indent_level + f"{old_var} = {old_src}")
            ctx.lines[old_marker_idx:old_marker_idx] = old_lines

    ctx.fn_name_stack.pop()
    ctx.old_exprs_stack.pop()
    ctx.ensures_stack.pop()


def emit_ensures_checks(ctx: EmitContext):
    """Emit one _ae_assert_contract call per active ensures clause.
    Called immediately before each `return _ae_result`."""
    if not ctx.ensures_stack or not ctx.ensures_stack[-1]:
        return
    fn_name = ctx.fn_name_stack[-1] if ctx.fn_name_stack else "?"
    for clause in ctx.ensures_stack[-1]:
        cond_src = emit_expr(ctx, clause)
        ctx.emit(f"_ae_assert_contract(bool({cond_src}), 'ensures', "
                 f"{repr(_pretty(clause))}, {fn_name!r})")


def _body_terminates(stmts: List[Dict[str, Any]]) -> bool:
    """Conservative check: returns True if every control-flow path through
    `stmts` ends in a Return / Break / Continue and the implicit fall-through
    cannot be reached. Used to suppress emission of the dead-code fall-through
    block (which would also create a redundant old() snapshot)."""
    if not stmts:
        return False
    last = stmts[-1]
    k = last.get("kind")
    if k in ("Return", "Break", "Continue"):
        return True
    if k == "If":
        # Terminates iff every branch terminates.
        if last.get("else") is None:
            return False
        if not _body_terminates(last["then"]):
            return False
        for e in last.get("elifs", []):
            if not _body_terminates(e["body"]):
                return False
        if not _body_terminates(last["else"]):
            return False
        return True
    if k == "Match":
        # Terminates iff every arm terminates. (Aether's match is exhaustive
        # per the spec, so no `else` is needed.)
        arms = last.get("arms", [])
        if not arms:
            return False
        return all(_body_terminates(a["body"]) for a in arms)
    return False


# ----------------------------------------------------------------------
# Statement / block
# ----------------------------------------------------------------------

def emit_block(ctx: EmitContext, stmts: List[Dict[str, Any]]):
    if not stmts:
        ctx.emit("pass")
        return
    for s in stmts:
        emit_stmt(ctx, s)


def emit_stmt(ctx: EmitContext, s: Dict[str, Any]):
    k = s["kind"]
    if k in ("Let", "Var"):
        ctx.emit(f"{mangle(s['name'])} = {emit_expr(ctx, s['value'])}")
    elif k == "Assign":
        ctx.emit(f"{mangle(s['target'])} = {emit_expr(ctx, s['value'])}")
    elif k == "If":
        emit_if_stmt(ctx, s)
    elif k == "While":
        ctx.emit(f"while {emit_expr(ctx, s['cond'])}:")
        with ctx.block():
            emit_block(ctx, s["body"])
    elif k == "For":
        ctx.emit(f"for {mangle(s['var'])} in {emit_expr(ctx, s['iter'])}:")
        with ctx.block():
            emit_block(ctx, s["body"])
    elif k == "Match":
        emit_match_stmt(ctx, s)
    elif k == "Return":
        emit_return(ctx, s)
    elif k == "Break":
        ctx.emit("break")
    elif k == "Continue":
        ctx.emit("continue")
    elif k == "ExprStmt":
        ctx.emit(emit_expr(ctx, s["expr"]))
    else:
        raise NotImplementedError(f"stmt kind: {k}")


def emit_if_stmt(ctx: EmitContext, s: Dict[str, Any]):
    ctx.emit(f"if {emit_expr(ctx, s['cond'])}:")
    with ctx.block():
        emit_block(ctx, s["then"])
    for e in s["elifs"]:
        ctx.emit(f"elif {emit_expr(ctx, e['cond'])}:")
        with ctx.block():
            emit_block(ctx, e["body"])
    if s["else"] is not None:
        ctx.emit("else:")
        with ctx.block():
            emit_block(ctx, s["else"])


def emit_match_stmt(ctx: EmitContext, s: Dict[str, Any]):
    scrut_var = ctx.fresh("scrut")
    ctx.emit(f"{scrut_var} = {emit_expr(ctx, s['scrutinee'])}")
    first = True
    for arm in s["arms"]:
        pat_cond, bindings = compile_pattern(ctx, arm["pattern"], scrut_var)
        kw = "if" if first else "elif"
        first = False
        ctx.emit(f"{kw} {pat_cond}:")
        with ctx.block():
            for var, expr in bindings:
                ctx.emit(f"{var} = {expr}")
            emit_block(ctx, arm["body"])
    ctx.emit("else:")
    with ctx.block():
        ctx.emit(f"raise RuntimeError('non-exhaustive match on ' + repr({scrut_var}))")


def emit_return(ctx: EmitContext, s: Dict[str, Any]):
    if s["value"] is None:
        ctx.emit("_ae_result = None")
    else:
        ctx.emit(f"_ae_result = {emit_expr(ctx, s['value'])}")
    emit_ensures_checks(ctx)
    ctx.emit("return _ae_result")


# ----------------------------------------------------------------------
# Patterns
# ----------------------------------------------------------------------

def compile_pattern(ctx: EmitContext, pat: Dict[str, Any], target: str):
    k = pat["kind"]
    if k == "WildcardPat":
        return ("True", [])
    if k == "BindPat":
        return ("True", [(mangle(pat["name"]), target)])
    if k == "LiteralPat":
        if pat.get("lit_kind") == "string":
            return (f"({target} == {pat['value']!r})", [])
        if pat.get("lit_kind") == "kw":
            mp = {"true": "True", "false": "False", "null": "None"}
            return (f"({target} is {mp[pat['value']]})", [])
        return (f"({target} == {pat['value']!r})", [])
    if k == "ConstructorPat":
        case_name = pat["path"][-1]
        conds = [
            f"isinstance({target}, tuple)",
            f"len({target}) >= 1",
            f"{target}[0] == {case_name!r}",
        ]
        bindings: List[Tuple[str, str]] = []
        n = len(pat["args"])
        conds.append(f"len({target}) == {n + 1}")
        for i, sub in enumerate(pat["args"]):
            sub_target = f"{target}[{i + 1}]"
            sub_cond, sub_bindings = compile_pattern(ctx, sub, sub_target)
            if sub_cond != "True":
                conds.append(sub_cond)
            bindings.extend(sub_bindings)
        return (" and ".join(f"({c})" for c in conds), bindings)
    if k == "AsPat":
        cond, bindings = compile_pattern(ctx, pat["pattern"], target)
        bindings = list(bindings) + [(mangle(pat["name"]), target)]
        return (cond, bindings)
    raise NotImplementedError(f"pattern kind: {k}")


# ----------------------------------------------------------------------
# Expressions
# ----------------------------------------------------------------------

PY_BINOPS = {
    "+": "+", "-": "-", "*": "*", "%": "%",
    "==": "==", "!=": "!=", "<": "<", "<=": "<=", ">": ">", ">=": ">=",
    "and": "and", "or": "or",
    "band": "&", "bor": "|", "bxor": "^", "shl": "<<", "shr": ">>",
}


def emit_expr(ctx: EmitContext, e: Dict[str, Any]) -> str:
    k = e["kind"]
    if k == "IntLit":
        return repr(e["value"])
    if k == "FloatLit":
        return repr(e["value"])
    if k == "StringLit":
        return repr(e["value"])
    if k == "BoolLit":
        return "True" if e["value"] else "False"
    if k == "NullLit":
        return "None"
    if k == "Ident":
        if e["name"] == "result":
            return "_ae_result"
        return mangle(e["name"])
    if k == "BinOp":
        op = e["op"]
        l = emit_expr(ctx, e["left"])
        r = emit_expr(ctx, e["right"])
        if op == "*":
            return f"({l} * {r})"
        if op == "/":
            return (f"((lambda __a, __b: (__a // __b) if "
                    f"(isinstance(__a, int) and isinstance(__b, int)) "
                    f"else (__a / __b))({l}, {r}))")
        if op == "implies":
            return f"((not ({l})) or ({r}))"
        if op == "is":
            type_name = e["right"].get("name") if e["right"].get("kind") == "Ident" else None
            if type_name == "Int":
                return f"(isinstance({l}, int) and not isinstance({l}, bool))"
            if type_name == "Float":
                return f"isinstance({l}, float)"
            if type_name == "String":
                return f"isinstance({l}, str)"
            if type_name == "Bool":
                return f"isinstance({l}, bool)"
            return f"(isinstance({l}, tuple) and len({l}) >= 1 and {l}[0] == {type_name!r})"
        if op == "in":
            return f"({l} in {r})"
        py = PY_BINOPS.get(op)
        if py is None:
            raise NotImplementedError(f"binop: {op}")
        return f"({l} {py} {r})"
    if k == "UnaryOp":
        v = emit_expr(ctx, e["value"])
        if e["op"] == "neg":
            return f"(-{v})"
        if e["op"] == "not":
            return f"(not {v})"
        raise NotImplementedError(f"unop: {e['op']}")
    if k == "Call":
        func_src = emit_callee(ctx, e["func"])
        args = ", ".join(emit_expr(ctx, a) for a in e["args"])
        return f"{func_src}({args})"
    if k == "Field":
        v = emit_expr(ctx, e["value"])
        return f"{v}[{e['name']!r}]"
    if k == "Index":
        v = emit_expr(ctx, e["value"])
        i = emit_expr(ctx, e["index"])
        return f"{v}[{i}]"
    if k == "ListLit":
        elems = ", ".join(emit_expr(ctx, x) for x in e["elems"])
        return f"[{elems}]"
    if k == "MapLit":
        items = ", ".join(
            f"{emit_expr(ctx, ent['key'])}: {emit_expr(ctx, ent['value'])}"
            for ent in e["entries"]
        )
        return "{" + items + "}"
    if k == "IfExpr":
        c = emit_expr(ctx, e["cond"])
        t = emit_expr(ctx, e["then"])
        else_v = emit_expr(ctx, e["else"])
        for ee in reversed(e["elifs"]):
            cc = emit_expr(ctx, ee["cond"])
            vv = emit_expr(ctx, ee["value"])
            else_v = f"({vv} if {cc} else {else_v})"
        return f"({t} if {c} else {else_v})"
    if k == "MatchExpr":
        return emit_match_expr(ctx, e)
    if k == "Old":
        var = ctx.fresh("old")
        if not ctx.old_exprs_stack:
            raise NotImplementedError("old() outside a function")
        src = emit_expr(ctx, e["value"])
        ctx.old_exprs_stack[-1].append((var, src))
        return var
    raise NotImplementedError(f"expr kind: {k}")


def emit_callee(ctx: EmitContext, callee: Dict[str, Any]) -> str:
    """Resolve constructor calls, including qualified ``Climate.Cold``."""
    if callee["kind"] == "Field":
        inner = callee["value"]
        if inner.get("kind") == "Ident":
            field = callee["name"]
            if field in ctx.union_cases:
                return mangle(field)
    if callee["kind"] == "Ident" and callee["name"] in ctx.union_cases:
        return mangle(callee["name"])
    return emit_expr(ctx, callee)


def emit_match_expr(ctx: EmitContext, e: Dict[str, Any]) -> str:
    scrut_src = emit_expr(ctx, e["scrutinee"])
    fn = ctx.fresh("matchexpr")
    saved = ctx.lines
    ctx.lines = []
    saved_indent = ctx.indent_level
    ctx.indent_level = 0
    ctx.emit(f"def {fn}(_ae_scrut):")
    with ctx.block():
        first = True
        for arm in e["arms"]:
            cond, bindings = compile_pattern(ctx, arm["pattern"], "_ae_scrut")
            kw = "if" if first else "elif"
            first = False
            ctx.emit(f"{kw} {cond}:")
            with ctx.block():
                for var, expr in bindings:
                    ctx.emit(f"{var} = {expr}")
                ctx.emit(f"return {emit_expr(ctx, arm['value'])}")
        ctx.emit("else:")
        with ctx.block():
            ctx.emit("raise RuntimeError('non-exhaustive match expr')")
    helper_block = ctx.lines
    ctx.lines = saved
    ctx.indent_level = saved_indent
    ctx._pending_helpers.extend(helper_block)
    return f"{fn}({scrut_src})"


# ----------------------------------------------------------------------
# Pretty printer for diagnostics
# ----------------------------------------------------------------------

def _pretty(e):
    k = e["kind"]
    if k == "IntLit":
        return str(e["value"])
    if k == "BoolLit":
        return "true" if e["value"] else "false"
    if k == "NullLit":
        return "null"
    if k == "StringLit":
        return repr(e["value"])
    if k == "Ident":
        return e["name"]
    if k == "BinOp":
        return f"({_pretty(e['left'])} {e['op']} {_pretty(e['right'])})"
    if k == "UnaryOp":
        return f"({e['op']} {_pretty(e['value'])})"
    if k == "Call":
        return f"{_pretty(e['func'])}(...)"
    if k == "Field":
        return f"{_pretty(e['value'])}.{e['name']}"
    if k == "Old":
        return f"old({_pretty(e['value'])})"
    return f"<{k}>"
